pull_request_rules:
  - name: Automatic update for PRs
    conditions:
      - -conflict # skip PRs with conflicts
      - -draft # filter-out GH draft PRs
      - -closed
      - -merged
      - "#commits-behind>0"
      - label!=do-not-update
    actions:
      update:
  - name: Warn author on conflicts
    conditions:
      - conflict
    actions:
      comment:
        message: "@{{author}} this PR has conflicts 😩"
      label:
        add:
          - conflict
