repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-added-large-files # prevents adding large files
  - id: check-merge-conflict # prevents merge conflicts
  - id: detect-private-key # detects private keys
  - id: fix-byte-order-marker # fixes BOM
  - id: fix-encoding-pragma # fixes encoding pragma
  - id: no-commit-to-branch # prevents committing to protected branches
  - id: trailing-whitespace # prevents trailing whitespace

- repo: https://github.com/psf/black
  rev: 22.12.0
  hooks:
  - id: black
    language_version: python3.10

- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
  - id: isort

- repo: https://github.com/PyCQA/flake8
  rev: 6.0.0
  hooks:
  - id: flake8

- repo: https://github.com/returntocorp/semgrep
  rev: v1.30.0
  hooks:
  - id: semgrep
    language: python
    args: [
      "--error",
      "--config",
      "auto",
      "--exclude-rule",
      "python.lang.security.audit.subprocess-shell-true.subprocess-shell-true",
      "--exclude-rule",
      "yaml.github-actions.security.third-party-action-not-pinned-to-commit-sha.third-party-action-not-pinned-to-commit-sha",
      "--exclude-rule",
      "python.lang.security.audit.insecure-transport.requests.request-session-with-http.request-session-with-http",
    ]